name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Download a build artifact
        uses: action/download-artifact@v3.0.0
        with:
          name: api-go

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          labels: jeff-alura-gh-action
          push: true
          tags: foguinhoperuca/go_ci:${{ github.ref_name }}
